[versions]
agp = "8.10.1"
kotlin = "2.0.21"
coreKtx = "1.16.0"
leanback = "1.2.0"
glide = "4.16.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-leanback = { group = "androidx.leanback", name = "leanback", version.ref = "leanback" }
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }

androidx-media3-exoplayer = "androidx.media3:media3-exoplayer:1.7.1"
androidx-media3-ui = "androidx.media3:media3-ui:1.7.1"
androidx-media3-hls = "androidx.media3:media3-exoplayer-hls:1.7.1"


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

