package id.my.arfanivan.android_tvv2

object MovieList {
    val COUNTRY_CATEGORY = arrayOf(
        "Afghanistan",
        "Albania",
        "Algeria",
        "Andorra",
        "Angola",
        "Arab",
        "Argentina",
        "Aruba",
        "Australia",
        "Austria",
        "Azerbaijan",
        "Bahamas",
        "Bahrain",
        "Bangladesh",
        "Barbados",
        "Belarus",
        "Belgium",
        "Benin",
        "Bermuda",
        "Bolivia",
        "Bonaire, Sint Eustatius and Saba",
        "Bosnia and Herzegovina",
        "Brazil",
        "Brunei Darussalam",
        "Bulgaria",
        "Burkina Faso",
        "Cabo Verde",
        "Cambodia",
        "Cameroon",
        "Canada",
        "Chad",
        "Chile",
        "China",
        "Colombia",
        "Congo",
        "Congo, Democratic Republic of the",
        "Costa Rica",
        "Croatia",
        "Cuba",
        "Curaçao" ,
        "Cyprus",
        "Czechia",
        "Cote dIvoire",
        "Denmark",
        "Dominican Republic" ,
        "Ecuador",
        "Egypt",
        "El Salvador",
        "Equatorial Guinea",
        "Estonia",
        "Ethiopia",
        "Faroe Islands",
        "Finland",
        "France",
        "French Polynesia",
        "Gambia",
        "Georgia",
        "Germany",
        "Ghana",
        "Greece",
        "Guadeloupe",
        "Guam",
        "Guatemala",
        "Guinea",
        "Guyana",
        "Haiti",
        "Honduras",
        "Hong Kong",
        "Hungary",
        "Iceland",
        "India",
        "Indonesia" ,
        "Iran",
        "Ireland",
        "Israel",
        "Italy",
        "Jamaica",
        "Japan",
        "Kazakhstan",
        "Kenya",
        "Korea Utara",
        "Korea Selatan",
        "Kosovo",
        "Kuwait",
        "Kyrgyzstan",
        "Lao People's Democratic Republic",
        "Latvia",
        "Lebanon",
        "Liberia",
        "Libya",
        "Lithuania",
        "Luxembourg",
        "MK",
        "Macao",
        "Malaysia",
            "Maldives",
            "Mali",
            "Malta",
            "Martinique",
            "Mexico",
            "Moldova",
            "Monaco",
            "Mongolia",
            "Montenegro",
            "Morocco",
            "Mozambique",
            "Myanmar",
            "Namibia",
            "Nepal",
            "Netherlands",
            "New Zealand",
            "Nicaragua",
            "Niger",
            "Nigeria",
            "Norway",
            "Oman",
            "Pakistan",
            "Palestine, State of",
            "Panama",
            "Papua New Guinea",
            "Paraguay",
            "Peru",
            "Philippines",
            "Poland",
            "Portugal",
            "Puerto Rico",
            "Qatar",
            "Romania",
            "Russian Federation",
            "Rwanda",
            "Saint Kitts and Nevis",
            "Saint Lucia",
            "San Marino",
            "Senegal",
            "Serbia",
            "Singapore",
            "Sint Maarten bagian Belanda",
            "Slovakia",
            "Slovenia",
            "Somalia",
            "South Africa",
            "Spain",
            "Sri Lanka",
            "Sudan",
            "Suriname",
            "Sweden",
            "Switzerland",
            "Syrian Arab Republic",
            "Taiwan",
            "Tajikistan",
            "Tanzania",
            "Thailand",
            "Togo",
            "Trinidad and Tobago",
            "Turkmenistan",
            "Turkiye",
            "Uganda",
            "Ukraine",
            "United Kingdom",
            "United States",
            "Uruguay",
            "Uzbekistan",
            "VA",
            "Venezuela",
            "Vietnam",
            "Virgin Islands, British",
            "Western Sahara",
            "Yemen"
    )

    val categorizedMovies: Map<String, List<Movie>> by lazy {
        setupMovies()
    }

    private fun setupMovies(): Map<String, List<Movie>> {
        return mapOf(
            "Indonesia" to IndonesiaMovieList.movies,
            "Afghanistan" to AfghanistanMovieList.movies,
            "Albania" to AlbaniaMovieList.movies,
            "Algeria" to AlgeriaMovieList.movies,
            "Andorra" to AndorraMovieList.movies,
            "Angola" to AngolaMovieList.movies,
            "Arab" to ArabMovieList.movies,
            "Argentina" to ArgentinaMovieList.movies,
            "Aruba" to ArubaMovieList.movies,
            "Australia" to AustraliaMovieList.movies,
            "Austria" to AustriaMovieList.movies,
            "Azerbaijan" to AzerbaijanMovieList.movies,
            "Bahamas" to BahamasMovieList.movies,
            "Bahrain" to BahrainMovieList.movies,
            "Bangladesh" to BangladeshMovieList.movies,
            "Barbados" to BarbadosMovieList.movies,
            "Belarus" to BelarusMovieList.movies,
            "Belgium" to BelgiumMovieList.movies,
            "Benin" to BeninMovieList.movies,
            "Bermuda" to BermudaMovieList.movies,
            "Bolivia" to BoliviaMovieList.movies,
//            "Bonaire, Sint Eustatius and Saba" to BonaireSintEustatiusAndSabaMovieList.movies,
//            "Bosnia and Herzegovina" to BosniaAndHerzegovinaMovieList.movies,
//            "Brazil" to BrazilMovieList.movies,
//            "Brunei Darussalam" to BruneiDarussalamMovieList.movies,
//            "Bulgaria" to BulgariaMovieList.movies,
//            "Burkina Faso" to BurkinaFasoMovieList.movies,
//            "Cabo Verde" to CaboVerdeMovieList.movies,
//            "Cambodia" to CambodiaMovieList.movies,
//            "Cameroon" to CameroonMovieList.movies,
            "Canada" to CanadaMovieList.movies,
//            "Chad" to ChadMovieList.movies,
//            "Chile" to ChileMovieList.movies,
            "China" to ChinaMovieList.movies,
//            "Colombia" to ColombiaMovieList.movies,
//            "Congo" to CongoMovieList.movies,
//            "Congo, Democratic Republic of the" to CongoDemocraticRepublicOfTheMovieList.movies,
//            "Costa Rica" to CostaRicaMovieList.movies,
//            "Croatia" to CroatiaMovieList.movies,
//            "Cuba" to CubaMovieList.movies,
//            "Curaçao" to CuracaoMovieList.movies,
//            "Cyprus" to CyprusMovieList.movies,
//            "Czechia" to CzechiaMovieList.movies,
//            "Cote dIvoire" to CoteDivoireMovieList.movies,
//            "Denmark" to DenmarkMovieList.movies,
//            "Dominican Republic" to DominicanRepublicMovieList.movies,
//            "Ecuador" to EcuadorMovieList.movies,
//            "Egypt" to EgyptMovieList.movies,
//            "El Salvador" to ElSalvadorMovieList.movies,
//            "Equatorial Guinea" to EquatorialGuineaMovieList.movies,
//            "Estonia" to EstoniaMovieList.movies,
//            "Ethiopia" to EthiopiaMovieList.movies,
//            "Faroe Islands" to FaroeIslandsMovieList.movies,
            "Finland" to FinlandMovieList.movies,
            "France" to FranceMovieList.movies,
            "French Polynesia" to FrenchPolynesiaMovieList.movies,
//            "Gambia" to GambiaMovieList.movies,
//            "Georgia" to GeorgiaMovieList.movies,
//            "Germany" to GermanyMovieList.movies,
//            "Ghana" to GhanaMovieList.movies,
//            "Greece" to GreeceMovieList.movies,
//            "Guadeloupe" to GuadeloupeMovieList.movies,
//            "Guam" to GuamMovieList.movies,
//            "Guatemala" to GuatemalaMovieList.movies,
//            "Guinea" to GuineaMovieList.movies,
//            "Guyana" to GuyanaMovieList.movies,
//            "Haiti" to HaitiMovieList.movies,
//            "Honduras" to HondurasMovieList.movies,
            "Hong Kong" to HongKongMovieList.movies,
//            "Hungary" to HungaryMovieList.movies,
//            "Iceland" to IcelandMovieList.movies,
            "India" to IndiaMovieList.movies,
            "Iran" to IranMovieList.movies,
//            "Ireland" to IrelandMovieList.movies,
//            "Israel" to IsraelMovieList.movies,
//            "Italy" to ItalyMovieList.movies,
//            "Jamaica" to JamaicaMovieList.movies,
            "Japan" to JapanMovieList.movies,
//            "Kazakhstan" to KazakhstanMovieList.movies,
//            "Kenya" to KenyaMovieList.movies,
            "Korea Utara" to KoreademocraticPeoplesRepublicOfMovieList.movies,
            "Korea Selatan" to KoreaRepublicOfMovieList.movies,
//            "Kosovo" to KosovoMovieList.movies,
//            "Kuwait" to KuwaitMovieList.movies,
//            "Kyrgyzstan" to KyrgyzstanMovieList.movies,
//            "Lao People's Democratic Republic" to LaoPeoplesDemocraticRepublicMovieList.movies,
//            "Latvia" to LatviaMovieList.movies,
//            "Lebanon" to LebanonMovieList.movies,
//            "Liberia" to LiberiaMovieList.movies,
            "Libya" to LibyaMovieList.movies,
//            "Lithuania" to LithuaniaMovieList.movies,
//            "Luxembourg" to LuxembourgMovieList.movies,
//            "MK" to MkMovieList.movies,
//            "Macao" to MacaoMovieList.movies,
            "Malaysia" to MalaysiaMovieList.movies,
//            "Maldives" to MaldivesMovieList.movies,
//            "Mali" to MaliMovieList.movies,
//            "Malta" to MaltaMovieList.movies,
//            "Martinique" to MartiniqueMovieList.movies,
//            "Mexico" to MexicoMovieList.movies,
//            "Moldova" to MoldovaMovieList.movies,
//            "Monaco" to MonacoMovieList.movies,
//            "Mongolia" to MongoliaMovieList.movies,
//            "Montenegro" to MontenegroMovieList.movies,
//            "Morocco" to MoroccoMovieList.movies,
//            "Mozambique" to MozambiqueMovieList.movies,
//            "Myanmar" to MyanmarMovieList.movies,
//            "Namibia" to NamibiaMovieList.movies,
//            "Nepal" to NepalMovieList.movies,
//            "Netherlands" to NetherlandsMovieList.movies,
//            "New Zealand" to NewZealandMovieList.movies,
//            "Nicaragua" to NicaraguaMovieList.movies,
//            "Niger" to NigerMovieList.movies,
//            "Nigeria" to NigeriaMovieList.movies,
//            "Norway" to NorwayMovieList.movies,
//            "Oman" to OmanMovieList.movies,
            "Pakistan" to PakistanMovieList.movies,
            "Palestine" to PalestineStateOfMovieList.movies,
//            "Panama" to PanamaMovieList.movies,
//            "Papua New Guinea" to PapuaNewGuineaMovieList.movies,
//            "Paraguay" to ParaguayMovieList.movies,
//            "Peru" to PeruMovieList.movies,
            "Philippines" to PhilippinesMovieList.movies,
//            "Poland" to PolandMovieList.movies,
//            "Portugal" to PortugalMovieList.movies,
//            "Puerto Rico" to PuertoRicoMovieList.movies,
//            "Qatar" to QatarMovieList.movies,
//            "Romania" to RomaniaMovieList.movies,
            "Russian Federation" to RussianFederationMovieList.movies,
//            "Rwanda" to RwandaMovieList.movies,
//            "Saint Kitts and Nevis" to SaintKittsAndNevisMovieList.movies,
//            "Saint Lucia" to SaintLuciaMovieList.movies,
//            "San Marino" to SanMarinoMovieList.movies,
//            "Senegal" to SenegalMovieList.movies,
//            "Serbia" to SerbiaMovieList.movies,
            "Singapore" to SingaporeMovieList.movies,
//            "Sint Maarten bagian Belanda" to SintMaartendutchPartMovieList.movies,
//            "Slovakia" to SlovakiaMovieList.movies,
//                "Slovenia" to SloveniaMovieList.movies,
//                "Somalia" to SomaliaMovieList.movies,
//                "South Africa" to SouthAfricaMovieList.movies,
//                "Spain" to SpainMovieList.movies,
//                "Sri Lanka" to SriLankaMovieList.movies,
//                "Sudan" to SudanMovieList.movies,
//                "Suriname" to SurinameMovieList.movies,
//                "Sweden" to SwedenMovieList.movies,
//                "Switzerland" to SwitzerlandMovieList.movies,
//                "Syrian Arab Republic" to SyrianArabRepublicMovieList.movies,
                "Taiwan" to TaiwanMovieList.movies,
//                "Tajikistan" to TajikistanMovieList.movies,
//                "Tanzania" to TanzaniaMovieList.movies,
//                "Thailand" to ThailandMovieList.movies,
//                "Togo" to TogoMovieList.movies,
//                "Trinidad and Tobago" to TrinidadAndTobagoMovieList.movies,
//                "Turkmenistan" to TurkmenistanMovieList.movies,
                "Turkiye" to TurkiyeMovieList.movies,
//                "Uganda" to UgandaMovieList.movies,
//                "Ukraine" to UkraineMovieList.movies,
//                "United Kingdom" to UnitedKingdomMovieList.movies,
//                "United States" to UnitedStatesMovieList.movies,
//                "Uruguay" to UruguayMovieList.movies,
//                "Uzbekistan" to UzbekistanMovieList.movies,
//                "VA" to VaMovieList.movies,
//                "Venezuela" to VenezuelaMovieList.movies,
                "Vietnam" to VietnamMovieList.movies,
//                "Virgin Islands, British" to VirginIslandsBritishMovieList.movies,
//                "Western Sahara" to WesternSaharaMovieList.movies,
//                "Yemen" to YemenMovieList.movies
        )
    }
}
